# @package _global_
defaults:
- _self_
- method: lw_adamerging # sum, tw_adamerging, lw_adamerging, ties, emr

model: ViT-B-32
num_tasks: 8
specify_lambda: None

# DATASETS: [DTD, Cars] 

# DATASETS: [DTD, Cars, RESISC45, EuroSAT, SVHN, GTSRB, MNIST, SUN397]
DATASETS: [SUN397, Cars, RESISC45, EuroSAT, SVHN, GTSRB, MNIST, DTD]

# utilities
cache_dir: None
world_size: 1
port: 12355
n_eval_points: 21
device: "cuda"
batch_size: 128
data_location: "data"
model_location: "checkpoints"

wandb:
  project: task-vectors
  mode: online
  group: ${model}

hydra:
  run:
    dir: ./logs/${model}/${method.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
